###
POST http://localhost:5000/api/users/register HTTP/1.1
content-type: application/json

{
  "name": "dongxin",
  "email": "dongxin2019@gmail.com",
  "password": "123456"
}
###
POST http://localhost:5000/api/users/login HTTP/1.1
content-type: application/json

{
  "email": "dongxin2019@gmail.com",
  "password": "123456"
}

###
GET http://localhost:5000/api/users/current HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjVkNGFkZDRlYThhMmMyMmQ0YWNkNjlkNyIsIm5hbWUiOiJkb25neGluIiwiYXZhdGFyIjoiLy93d3cuZ3JhdmF0YXIuY29tL2F2YXRhci8wOTAzZjEwODMwOTgzODc2ZmY4ZTJiY2IwMDZhYzYwYT9zPTIwMCZyPXBnJmQ9bW0iLCJpYXQiOjE1NjUxOTUwNzcsImV4cCI6MTU2NTE5ODY3N30.zPT2s4dNvXceFvKsmR0gVjHG4UDzkKcceiEM1r75DVs

###
POST http://localhost:5000/api/profiles/add HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjVkNGFkZDRlYThhMmMyMmQ0YWNkNjlkNyIsIm5hbWUiOiJkb25neGluIiwiYXZhdGFyIjoiLy93d3cuZ3JhdmF0YXIuY29tL2F2YXRhci8wOTAzZjEwODMwOTgzODc2ZmY4ZTJiY2IwMDZhYzYwYT9zPTIwMCZyPXBnJmQ9bW0iLCJpYXQiOjE1NjUxOTUwNzcsImV4cCI6MTU2NTE5ODY3N30.zPT2s4dNvXceFvKsmR0gVjHG4UDzkKcceiEM1r75DVs

{
  "type": "优惠卷",
  "describe": "购买课程",
  "income": "200",
  "expend": "2000",
  "cash": "50000",
  "remark": "购买课程"
}

###
GET http://localhost:5000/api/profiles HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjVkNGFkZDRlYThhMmMyMmQ0YWNkNjlkNyIsIm5hbWUiOiJkb25neGluIiwiYXZhdGFyIjoiLy93d3cuZ3JhdmF0YXIuY29tL2F2YXRhci8wOTAzZjEwODMwOTgzODc2ZmY4ZTJiY2IwMDZhYzYwYT9zPTIwMCZyPXBnJmQ9bW0iLCJpYXQiOjE1NjUxOTUwNzcsImV4cCI6MTU2NTE5ODY3N30.zPT2s4dNvXceFvKsmR0gVjHG4UDzkKcceiEM1r75DVs


###
GET http://localhost:5000/api/profiles/5d4b019b8a7db52ca2896bd7 HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjVkNGFkZDRlYThhMmMyMmQ0YWNkNjlkNyIsIm5hbWUiOiJkb25neGluIiwiYXZhdGFyIjoiLy93d3cuZ3JhdmF0YXIuY29tL2F2YXRhci8wOTAzZjEwODMwOTgzODc2ZmY4ZTJiY2IwMDZhYzYwYT9zPTIwMCZyPXBnJmQ9bW0iLCJpYXQiOjE1NjUxOTUwNzcsImV4cCI6MTU2NTE5ODY3N30.zPT2s4dNvXceFvKsmR0gVjHG4UDzkKcceiEM1r75DVs

###
POST http://localhost:5000/api/profiles/edit/5d4b019b8a7db52ca2896bd7 HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjVkNGFkZDRlYThhMmMyMmQ0YWNkNjlkNyIsIm5hbWUiOiJkb25neGluIiwiYXZhdGFyIjoiLy93d3cuZ3JhdmF0YXIuY29tL2F2YXRhci8wOTAzZjEwODMwOTgzODc2ZmY4ZTJiY2IwMDZhYzYwYT9zPTIwMCZyPXBnJmQ9bW0iLCJpYXQiOjE1NjUxOTUwNzcsImV4cCI6MTU2NTE5ODY3N30.zPT2s4dNvXceFvKsmR0gVjHG4UDzkKcceiEM1r75DVs

###
DELETE http://localhost:5000/api/profiles/delete/5d4b013ca2a0134706d38e5b HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjVkNGFkZDRlYThhMmMyMmQ0YWNkNjlkNyIsIm5hbWUiOiJkb25neGluIiwiYXZhdGFyIjoiLy93d3cuZ3JhdmF0YXIuY29tL2F2YXRhci8wOTAzZjEwODMwOTgzODc2ZmY4ZTJiY2IwMDZhYzYwYT9zPTIwMCZyPXBnJmQ9bW0iLCJpYXQiOjE1NjUxOTUwNzcsImV4cCI6MTU2NTE5ODY3N30.zPT2s4dNvXceFvKsmR0gVjHG4UDzkKcceiEM1r75DVs
